### PR TITLE
Update for Express 4.x

### PR DESCRIPTION
**Pull request by vincentpeyrouse**
- Usage of connect module removed
- External modules (cookie-parser and express-session) added
- Format of route in router stack adapted

### CODE REVIEW

**Comment by techpines** [comment]
Awesome.

I'll need to do some testing, but I'd like to merge this.

**Comment by vincentpeyrouse** [comment]
Thank you.

I didn't test it a lot (in other words, i just tested if server start with my mods...).

I'll make some other tests on tomorrow and write back here soon :)

**Comment by vincentpeyrouse** [comment]
Commit 8aabf2e : Route for socket.io handling in express router where passed as simple object and i was getting "Object has not method: match" error.

Now the route is inserted as a Layer in stack, like express mechanics used to.

**Comment by Analogreality** [comment]
What's the state on this.. does it play nicely with Express v4?

**Comment by techpines** [comment]
Our next release is going to be for express 4.x and socket.io 1.x.  

I like what @GodezInc has done so far, but I think it makes sense to just upgrade both versions at once.  I'm trying to figure out what needs to change for socket.io 1.x, and whether it makes sense to merge this PR.

**Comment by andrewtheone** [comment]
So, when do we get the updates? Will the api remain the same, I'd hope so :)

**Comment by benkaiser** [comment]
any ETA on this merge?

**Comment by Anachron** [comment]
Another BUMP, any ETA?

**Comment by techpines** [comment]
@GodezInc I'm having some issues with this PR not working.  Specifically, I'm getting this error when I try to run a simple example:

```
/tmp/express.io/lib/index.coffee:211
    this._router.stack.push(layer);
                ^
TypeError: Cannot read property 'stack' of undefined
    at Function.express.application.io (/tmp/express.io/lib/index.coffee:211:17)
    at Object.<anonymous> (/tmp/express.io/examples/http-io/app.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by Anachron** [comment]
@godezInc can you take a look? Maybe a commit missing?

**Comment by vincentpeyrouse** [comment]
What is the version of express ?
(I used express@4.4.0 as a baseline and tested it with success on 4.4.1 too)

**Comment by techpines** [comment]
I was using 4.5, although I'm seeing the same thing in 4.4.

What line of code do you even define `this._router`:

https://github.com/GodezInc/express.io/blob/master/lib/index.coffee#L126

Also this is how I installed your branch:

```
git clone git@github.com:GodezInc/express.io.git
cd express.io
npm install
```

Hope that helps.

**Comment by vincentpeyrouse** [comment]
I retrieve _router directly from express https://github.com/visionmedia/express/blob/master/lib/application.js#L100

I just redeploy my project with a fresh `npm install` (i got express 4.5.1) and it works.

Partial npm tree :
├─┬ express.io@1.1.14
│ ├─┬ express@4.5.1

node 0.10.29, npm 1.4.14, OS X yosemite

**Comment by techpines** [comment]
Yea, I don't think the problem is with versions.

Is it possible that your setup is slightly different, and that for some reason in my test examples `app.lazyrouter()` is not getting called, and so `this._router` is not getting defined?

Here is the code I'm trying to run:

```
var express = require('express.io');
var app = express().http().io();
app.listen(7076);
```

**Comment by vincentpeyrouse** [comment]
I was writing about `app.lazyrouter()` when i saw the email notification :)

Indeed, it seems that's because you're not using `app.use`, `app.router` or other methods like these.

**Comment by techpines** [comment]
So, I think if we added this line right above `index.coffee@L126` that would fix that issue:

``` coffee
@lazyrouter() unless @_router?
```

Then the only other thing that seems broken is the sessions themselves.   I can't seem to get this example to work:

https://github.com/techpines/express.io/tree/master/examples/sessions

**Comment by vincentpeyrouse** [comment]
It's maybe related with log messages :

<pre><code>express-session deprecated undefined resave option; provide resave option
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option</code></pre>

**Comment by techpines** [comment]
Cool, I'm going to merge this for now, since I think it's mostly correct.

Then it's just a matter of figuring out the last remaining issue on the sessions before it goes live to npm.

**Comment by Anachron** [comment]
Don't forget to bump the version @techpines ! :)

**Comment by benkaiser** [comment]
bump for the version bump / npm update ;) @techpines

**Comment by benkaiser** [comment]
@techpines any eta on this?

**Comment by autoferrit** [comment]
What is needed to get this latest version running for an app, so use with express 4?

**Comment by davidbenhaim** [comment]
if you install from npm it won't work with express 4 b/c version isn't updated. 

had to do `npm install --save https://github.com/techpines/express.io` to get it to work

**Pull request merged**
